indexing_tool = "{haxorg_root}/build/utils_debug/reflection_tool"
toolchain_include = "{haxorg_root}/toolchain/llvm/lib/clang/17/include"
output_directory = "{config_dir}/src/hlibgit2"
input = [ "{config_dir}/libgit2/include" ]
build_root = "{config_dir}/libgit2/build"
source_root = "{config_dir}/libgit2"
header_root = "{config_dir}/libgit2/include/git2"
cmake_configure_options = ["-DBUILD_TESTS=OFF"]

[nim]
function_renames = [
  { original = "git_odb_write_pack", renamed = "git_odb_write_pack_fn" }
]

universal_import = [
  "libgit2_config.nim"
]
